### ISSUE TITLE
Your Contact

### ISSUE THREAD

**Issue by nisarhassan12** [zainulabidin302/oct-compute#1]
Asalam-o-Alaikum. I hope that you're well. I'm Nisar

Sorry for the spammy issue I just wanted to contact you. Can you provide me with your email if your comfortable ? I had your phone number but that does not work I tried it many times. 

I'm Syed Nisar Hassan and we met in UMT back in 2017 or maybe the start of 2018. Thanks

**Comment by zainulabidin302** [comment]
zainulabidin302@gmail.comOn 03-Jan-2021 2:34 AM, Nisar Hassan Naqvi <notifications@github.com> wrote:
Asalam-o-Alaikum. I hope that you're well. I'm Nisar
Sorry for the spammy issue I just wanted to contact you. Can you provide me with your email if your comfortable ?
I'm Syed Nisar Hassan and we met in UMT back in 2017 or maybe the start of 2018. Thanks

**Comment by nisarhassan12** [comment]
Thanks. I have now got your email so I will close this.
